# Generated by Django 4.2 on 2023-07-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_ban'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banadmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_banned', models.BooleanField(default=False)),
            ],
        ),
    ]
